spring:
  profiles:
    default: dev

---

spring:
  config:
    activate:
      on-profile: local

  # 스프링부트가 제공하는 내장 DB (H2, HSQL, Derdy) 를 사용할 경우 필요 없지만
  # 외부 DB를 사용 할 경우 true 로 해놔야 script(schema.sql, data.sql) 파일을 실행함
  sql:
    init:
      # 이거 없으면 mysql 인식 못함
      platform: mysql
      mode: never

  datasource:
    url: jdbc:mysql://localhost:3306/MarketBridge
    username: objects
    password: 1234

  jpa:
    show-sql: true

    # (2.5~) Hibernate 초기화 이후 data-mysql.sql 실행
    # 하이버네이트가 테이블들을 생성해주고, data.sql 로 데이터들을 초기화해줌 (ddl-auto 사용할때만 필요한 설정, schema.sql 따로 사용하면 필요없음)
    # defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate.sql: debug

payment:
  kakao:
    secret_key_dev : "DEVEC2152904951CB5CF3C5BEEBB3C84B6AD6F26"

host: "http://localhost:8080"

jwt:
  # CLI 명령어 - openssl rand -base64 64 로 생성된 값
  secret: fMRb9kle/ImDQ7wB8+XPnuVH15M6xp60jKS7/mF7dNMFEvt9kNe4WioJfsHT6J6F4bynR8rqAR2Z8zYboQSG+A==

---

spring:
  config:
    activate:
      on-profile: test

  data:
    redis:
      host: localhost
      port: 6379

  sql:
    init:
      mode: always
      platform: h2

  datasource:
    url: jdbc:h2:mem:~/Marketbridge
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.sql: debug

payment:
  kakao:
    secret_key_dev : "DEVEC2152904951CB5CF3C5BEEBB3C84B6AD6F26"

host: "http://localhost:8080"

jwt:
  secret: fMRb9kle/ImDQ7wB8+XPnuVH15M6xp60jKS7/mF7dNMFEvt9kNe4WioJfsHT6J6F4bynR8rqAR2Z8zYboQSG+A==

---

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.sql: debug

payment:
  kakao:
    secret_key_dev : "DEVEC2152904951CB5CF3C5BEEBB3C84B6AD6F26"

decorator:
  datasource:
    p6spy:
      enable-logging: false