spring:
  profiles:
    default: local

---
spring:
  config:
    activate:
      on-profile: local

  sql:
    init:
      mode: always
      platform: mysql # 이거 없으면 mysql 인식 못함

  jwt: # CLI 명령어 - openssl rand -base64 32 로 생성된 값
    secret: VZvl0mIgwU2UmDMXqa7CL79kdBUYz+IvHQWmNsWT4uA=

  datasource:
    url: jdbc:mysql://localhost:3306/MarketBridge
    username: objects
    password: 1234

#datasource:
#url: jdbc:h2:tcp://localhost/~/Marketbridge
#username: sa
#password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true # (2.5~) Hibernate 초기화 이후 data-mysql.sql 실행
    # 이게 없으면 data-mysql.sql 스크립트가 수행 안 되고 에러 발생합니당.

  h2:
    console:
      enabled: true

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate.sql: debug

payment:
  kakao:
    client_id : "AE7564ADF66B30123C2A"
    client_secret : "94B65EF567BCB6E860B4"
    secret_key: "PRD4A3CDADAF6C09168BA3E4725A3C678A78B271"
    secret_key_dev : "DEVEC2152904951CB5CF3C5BEEBB3C84B6AD6F26"

host: "http://localhost:8080"

---

spring:
  config:
    activate:
      on-profile: test

  data:
    redis:
      host: localhost
      port: 6379

  sql:
    init:
      mode: always
      platform: h2

  jwt: # CLI 명령어 - openssl rand -base64 32 로 생성된 값
    secret: VZvl0mIgwU2UmDMXqa7CL79kdBUYz+IvHQWmNsWT4uA=

  datasource:
#    url: jdbc:h2:tcp://localhost/~/Marketbridge
    url: jdbc:h2:mem:~/Marketbridge
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.sql: debug

payment:
  kakao:
    client_id : "AE7564ADF66B30123C2A"
    client_secret : "94B65EF567BCB6E860B4"
    secret_key: "PRD4A3CDADAF6C09168BA3E4725A3C678A78B271"
    secret_key_dev : "DEVEC2152904951CB5CF3C5BEEBB3C84B6AD6F26"

host: "http://localhost:8080/"
