spring:
  profiles:
    default: local

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/MarketBridge
    username: objects
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true # (2.5~) Hibernate 초기화 이후 data-mysql.sql 실행
    # 이게 없으면 data-mysql.sql 스크립트가 수행 안 되고 에러 발생합니당.

  h2:
    console:
      enabled: true

payment:
  toss:
    test_client_api_key : test_ck_GePWvyJnrK2PmxlyQWMqVgLzN97E
    test_secret_api_key : test_sk_QbgMGZzorzyG7E6ZkybPVl5E1em4
    success_url : "http://localhost:8080/toss/success"
    fail_url : "http://localhost:8080/toss/fail"
---

spring:
  config:
    activate:
      on-profile: test

  datasource:
#    url: jdbc:h2:tcp://localhost/~/Marketbridge
    url: jdbc:h2:mem:~/Marketbridge
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

  h2:
    console:
      enabled: true